"""Change in product and attribute ralationships

Revision ID: 2a34770ef05d
Revises: b9251cd0e5ce
Create Date: 2016-09-04 12:36:32.046118

"""

# revision identifiers, used by Alembic.
revision = '2a34770ef05d'
down_revision = 'b9251cd0e5ce'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_product_attributes', sa.Column('catalog_product_attribute_id', sa.Integer(), nullable=True))
    op.drop_index('idx_products_product_attributes_id', table_name='products_product_attributes')
    op.create_index('idx_products_product_attributes_id', 'products_product_attributes', ['product_id', 'catalog_product_attribute_id'], unique=False)
    op.drop_constraint('products_product_attributes_product_attribute_id_fkey', 'products_product_attributes', type_='foreignkey')
    op.create_foreign_key(None, 'products_product_attributes', 'catalog_product_attribute', ['catalog_product_attribute_id'], ['id'], onupdate='CASCADE')
    op.drop_column('products_product_attributes', 'product_attribute_id')
    op.drop_table('product_attribute')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_product_attributes', sa.Column('product_attribute_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products_product_attributes', type_='foreignkey')
    op.create_foreign_key('products_product_attributes_product_attribute_id_fkey', 'products_product_attributes', 'product_attribute', ['product_attribute_id'], ['id'], onupdate='CASCADE')
    op.drop_index('idx_products_product_attributes_id', table_name='products_product_attributes')
    op.create_index('idx_products_product_attributes_id', 'products_product_attributes', ['product_id', 'product_attribute_id'], unique=False)
    op.drop_column('products_product_attributes', 'catalog_product_attribute_id')
    op.create_table('product_attribute',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('product_attribute_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='product_attribute_pkey')
    )
    ### end Alembic commands ###
