"""Added filter column to product table for implement filters functionality

Revision ID: 7059627decb7
Revises: 5e48aa6fbb76
Create Date: 2016-12-12 12:21:05.561660

"""

# revision identifiers, used by Alembic.
revision = '7059627decb7'
down_revision = '5e48aa6fbb76'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('filters', postgresql.ARRAY(sa.Integer()), server_default=sa.text('ARRAY[]::integer[]'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'filters')
    ### end Alembic commands ###
