"""Added project description

Revision ID: 85c5657dc73e
Revises: 005735b54b04
Create Date: 2016-09-03 23:04:46.105472

"""

# revision identifiers, used by Alembic.
revision = '85c5657dc73e'
down_revision = '005735b54b04'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.Text(), nullable=False))
    op.create_index(op.f('ix_product_description'), 'product', ['description'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_description'), table_name='product')
    op.drop_column('product', 'description')
    ### end Alembic commands ###
