"""Added tables which products relates

Revision ID: 2b8c428ff744
Revises: 7a32a5248590
Create Date: 2016-08-27 23:22:04.350794

"""

# revision identifiers, used by Alembic.
revision = '2b8c428ff744'
down_revision = '7a32a5248590'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("create sequence product_id_seq start with 1 increment by 1")
    op.execute("create sequence product_attribute_id_seq start with 1 increment by 1")
    op.execute("create sequence product_fabric_id_seq start with 1 increment by 1")
    op.execute("create sequence product_manufacturer_id_seq start with 1 increment by 1")
    op.execute("create sequence product_photo_id_seq start with 1 increment by 1")
    op.create_table('product',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('product_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug_name', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug_name')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_index(op.f('ix_product_price'), 'product', ['price'], unique=False)
    op.create_table('product_attribute',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('product_attribute_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_attribute_id'), 'product_attribute', ['id'], unique=False)
    op.create_index(op.f('ix_product_attribute_name'), 'product_attribute', ['name'], unique=False)
    op.create_table('product_fabric',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('product_fabric_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_fabric_id'), 'product_fabric', ['id'], unique=False)
    op.create_index(op.f('ix_product_fabric_name'), 'product_fabric', ['name'], unique=False)
    op.create_table('product_manufacturer',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('product_manufacturer_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_manufacturer_id'), 'product_manufacturer', ['id'], unique=False)
    op.create_index(op.f('ix_product_manufacturer_name'), 'product_manufacturer', ['name'], unique=False)
    op.create_table('product_photo',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('product_photo_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('tumbl_name', sa.Text(), nullable=False),
    sa.Column('tumbl_path', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_photo_id'), 'product_photo', ['id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.schema.DropSequence(sa.Sequence("product_id_seq")))
    op.execute(sa.schema.DropSequence(sa.Sequence("product_attribute_id_seq")))
    op.execute(sa.schema.DropSequence(sa.Sequence("product_fabric_id_seq")))
    op.execute(sa.schema.DropSequence(sa.Sequence("product_manufacturer_id_seq")))
    op.execute(sa.schema.DropSequence(sa.Sequence("product_photo_id_seq")))
    op.drop_index(op.f('ix_product_photo_id'), table_name='product_photo')
    op.drop_table('product_photo')
    op.drop_index(op.f('ix_product_manufacturer_name'), table_name='product_manufacturer')
    op.drop_index(op.f('ix_product_manufacturer_id'), table_name='product_manufacturer')
    op.drop_table('product_manufacturer')
    op.drop_index(op.f('ix_product_fabric_name'), table_name='product_fabric')
    op.drop_index(op.f('ix_product_fabric_id'), table_name='product_fabric')
    op.drop_table('product_fabric')
    op.drop_index(op.f('ix_product_attribute_name'), table_name='product_attribute')
    op.drop_index(op.f('ix_product_attribute_id'), table_name='product_attribute')
    op.drop_table('product_attribute')
    op.drop_index(op.f('ix_product_price'), table_name='product')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    ### end Alembic commands ###
