"""Create table for feedbacks

Revision ID: 2e4dfa96470b
Revises: 7059627decb7
Create Date: 2016-12-25 18:56:06.520650

"""

# revision identifiers, used by Alembic.
revision = '2e4dfa96470b'
down_revision = '7059627decb7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_body',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_body')
    ### end Alembic commands ###
