"""Default value for user dates, Product.slug_name not nullable, refactoring ProductPhoto and some relationships

Revision ID: 5e48aa6fbb76
Revises: 465198720c97
Create Date: 2016-11-27 00:58:47.946882

"""

# revision identifiers, used by Alembic.
revision = '5e48aa6fbb76'
down_revision = '465198720c97'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_photo', 'large_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('product_photo', 'large_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('product_photo', 'small_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('product_photo', 'small_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('product_photo', 'thumb_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('product_photo', 'thumb_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'product_photo', ['large_path'])
    op.create_unique_constraint(None, 'product_photo', ['thumb_path'])
    op.create_unique_constraint(None, 'product_photo', ['small_path'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_photo', type_='unique')
    op.drop_constraint(None, 'product_photo', type_='unique')
    op.drop_constraint(None, 'product_photo', type_='unique')
    op.alter_column('product_photo', 'thumb_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('product_photo', 'thumb_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('product_photo', 'small_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('product_photo', 'small_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('product_photo', 'large_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('product_photo', 'large_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###
