"""Change nullable condition for password field and create is_created field for storing raw users

Revision ID: 9bec8172e53b
Revises: 2e4dfa96470b
Create Date: 2016-12-25 20:01:40.667992

"""

# revision identifiers, used by Alembic.
revision = '9bec8172e53b'
down_revision = '2e4dfa96470b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.add_column('user', sa.Column('is_created', sa.Boolean(), nullable=True))
    user = table('user', column('is_created'))
    op.execute(user.update().values(is_created=False))
    op.alter_column('user', 'is_created', nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('user', 'is_created')
    ### end Alembic commands ###
