"""Initial data model

Revision ID: 9efba819b4d4
Revises: 
Create Date: 2016-08-27 22:58:02.420895

"""

# revision identifiers, used by Alembic.
revision = '9efba819b4d4'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
	### commands auto generated by Alembic - please adjust! ###
	pass
	### end Alembic commands ###


def downgrade():
	### commands auto generated by Alembic - please adjust! ###
	pass
	### end Alembic commands ###
