"""Deleted excess essences

Revision ID: b9251cd0e5ce
Revises: 85c5657dc73e
Create Date: 2016-09-04 10:46:09.543673

"""

# revision identifiers, used by Alembic.
revision = 'b9251cd0e5ce'
down_revision = '85c5657dc73e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_product_attribute',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('product_attribute_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_product_attribute_id'), 'catalog_product_attribute', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_product_attribute_name'), 'catalog_product_attribute', ['name'], unique=False)
    op.drop_table('products_product_fabrics')
    op.drop_table('products_product_manufacturers')
    op.drop_table('product_fabric')
    op.drop_table('product_manufacturer')
    op.drop_index('ix_product_price', table_name='product')
    op.drop_column('product', 'price')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('price', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.create_index('ix_product_price', 'product', ['price'], unique=False)
    op.create_table('product_manufacturer',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('product_manufacturer_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='product_manufacturer_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('products_product_manufacturers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('products_product_manufacturers_id_seq'::regclass)"), nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_manufacturer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='products_product_manufacturers_product_id_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['product_manufacturer_id'], ['product_manufacturer.id'], name='products_product_manufacturers_product_manufacturer_id_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='products_product_manufacturers_pkey')
    )
    op.create_table('products_product_fabrics',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('products_product_fabrics_id_seq'::regclass)"), nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_fabric_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_fabric_id'], ['product_fabric.id'], name='products_product_fabrics_product_fabric_id_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='products_product_fabrics_product_id_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='products_product_fabrics_pkey')
    )
    op.create_table('product_fabric',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('product_fabric_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='product_fabric_pkey')
    )
    op.drop_index(op.f('ix_catalog_product_attribute_name'), table_name='catalog_product_attribute')
    op.drop_index(op.f('ix_catalog_product_attribute_id'), table_name='catalog_product_attribute')
    op.drop_table('catalog_product_attribute')
    ### end Alembic commands ###
