"""Added attribute value to catalog_product_attribute

Revision ID: f2482c2f3fce
Revises: 2a34770ef05d
Create Date: 2016-09-04 12:58:01.033334

"""

# revision identifiers, used by Alembic.
revision = 'f2482c2f3fce'
down_revision = '2a34770ef05d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_photo', sa.Column('thumb_name', sa.String(length=255), nullable=False))
    op.add_column('product_photo', sa.Column('thumb_path', sa.String(length=255), nullable=False))
    op.drop_column('product_photo', 'tumbl_path')
    op.drop_column('product_photo', 'tumbl_name')
    op.add_column('products_product_attributes', sa.Column('attribute_value', sa.String(length=255), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_product_attributes', 'attribute_value')
    op.add_column('product_photo', sa.Column('tumbl_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('product_photo', sa.Column('tumbl_path', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('product_photo', 'thumb_path')
    op.drop_column('product_photo', 'thumb_name')
    ### end Alembic commands ###
